var jsonObjects = {
		"ticket1": {
		"date" : ["Date Entered: ", "2013-03-04"],
		"firstn" : ["First Name: ", "RY"],
		"lastn" : ["Last Name: ", "Kingston"],
		"email" : ["Email Address: ", "r.d@palmedo.tv"],
		"phone" : ["Phone Number: ", "(949)585-1111"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "100"],
		"supportType" : ["Support Type: ", "Email"],
		"response" : ["Waiting for Response: ", "No"],
		"comments" : ["Support Overview: ", "NewsScroll was down.  After restarting system it's up and running again."]
	},
		"ticket2": {
		"date" : ["Date Entered: ", "2013-03-04"],
		"firstn" : ["First Name: ", "Kit"],
		"lastn" : ["Last Name: ", "Wheeler"],
		"email" : ["Email Address: ", "s.wheeler@comcast.tv"],
		"phone" : ["Phone Number: ", "(444)585-0055"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "40"],
		"supportType" : ["Support Type: ", "Sales_Inquiry"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "Compix board failed."]
	},
		"ticket3": {
		"date" : ["Date Entered: ", "2013-03-04"],
		"firstn" : ["First Name: ", "Kwangjo"],
		"lastn" : ["Last Name: ", "Ko"],
		"email" : ["Email Address: ", "kwangjo.ko@compix.tv"],
		"phone" : ["Phone Number: ", "(949)585-0055"],
		"contactType" : ["Contact Type: ", "Dealer"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "80"],
		"supportType" : ["Support Type: ", "Sales_Inquiry"],
		"response" : ["Waiting for Response: ", "No"],
		"comments" : ["Support Overview: ", "Called for pricing on item.  Wrote down phone number, will give it to sales."]
	},
		"ticket4": {
		"date" : ["Date Entered: ", "2013-03-04"],
		"firstn" : ["First Name: ", "Robert"],
		"lastn" : ["Last Name: ", "Evans"],
		"email" : ["Email Address: ", "robert.evans@fwisd.com"],
		"phone" : ["Phone Number: ", ""],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "20"],
		"supportType" : ["Support Type: ", "Support_Form"],
		"response" : ["Waiting for Response: ", "No"],
		"comments" : ["Support Overview: ", "Possible Defective power supply or motherboard."]
	},
		"ticket5": {
		"date" : ["Date Entered: ", "2013-03-03"],
		"firstn" : ["First Name: ", "Roger"],
		"lastn" : ["Last Name: ", "Creemers"],
		"email" : ["Email Address: ", "roger@nk2.nl"],
		"phone" : ["Phone Number: ", ""],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "50"],
		"supportType" : ["Support Type: ", "Call"],
		"response" : ["Waiting for Response: ", "No"],
		"comments" : ["Support Overview: ", "2 issues with system.  1: Key & Fill isn't aligned, 2: crawl stutters."]
	},
		"ticket6": {
		"date" : ["Date Entered: ", "2013-03-03"],
		"firstn" : ["First Name: ", "Jaehand"],
		"lastn" : ["Last Name: ", "Kim"],
		"email" : ["Email Address: ", "j.k@google.com"],
		"phone" : ["Phone Number: ", "(949)585-0056"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "75"],
		"supportType" : ["Support Type: ", "Support_Form"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "defective power supply"]
	},
		"ticket7": {
		"date" : ["Date Entered: ", "2013-03-03"],
		"firstn" : ["First Name: ", "Pat"],
		"lastn" : ["Last Name: ", "Turner"],
		"email" : ["Email Address: ", "p.t@yahoo.com"],
		"phone" : ["Phone Number: ", "(494)444-4444"],
		"contactType" : ["Contact Type: ", "Dealer"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "34"],
		"supportType" : ["Support Type: ", "Online_Chat"],
		"response" : ["Waiting for Response: ", "No"],
		"comments" : ["Support Overview: ", "question about system, power supply was defective.  Will order new PS."]
	},
		"ticket8": {
		"date" : ["Date Entered: ", "2013-03-02"],
		"firstn" : ["First Name: ", "Manuel"],
		"lastn" : ["Last Name: ", "Rhodes"],
		"email" : ["Email Address: ", "mr@compix.tv"],
		"phone" : ["Phone Number: ", "(949)585-0023"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "75"],
		"supportType" : ["Support Type: ", "Call"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "ToGO SDI not working correct, wants to send in."]
	},
		"ticket9": {
		"date" : ["Date Entered: ", "2013-03-01"],
		"firstn" : ["First Name: ", "Kimberly"],
		"lastn" : ["Last Name: ", "Kim"],
		"email" : ["Email Address: ", "kju123@psu.edu"],
		"phone" : ["Phone Number: ", "(454)345-0987"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "75"],
		"supportType" : ["Support Type: ", "Email"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "She called because she needs a registration code."]
	},
		"ticket10": {
		"date" : ["Date Entered: ", "2013-03-01"],
		"firstn" : ["First Name: ", "Michael"],
		"lastn" : ["Last Name: ", "Special"],
		"email" : ["Email Address: ", "michael.special@google.com"],
		"phone" : ["Phone Number: ", "(821)309-4859"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "50"],
		"supportType" : ["Support Type: ", "Sales_Inquiry"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "CompactCG Issues with sync."]
	},
		"ticket11": {
		"date" : ["Date Entered: ", "2013-03-01"],
		"firstn" : ["First Name: ", "Matt"],
		"lastn" : ["Last Name: ", "Eiberstiensier"],
		"email" : ["Email Address: ", "m.e@compix.tv"],
		"phone" : ["Phone Number: ", "(949)090-0000"],
		"contactType" : ["Contact Type: ", "Dealer"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "30"],
		"supportType" : ["Support Type: ", "Call"],
		"response" : ["Waiting for Response: ", "No"],
		"comments" : ["Support Overview: ", "Compix PC Issues, resolved."]
	},
		"ticket12": {
		"date" : ["Date Entered: ", "2013-03-01"],
		"firstn" : ["First Name: ", "Michael"],
		"lastn" : ["Last Name: ", "Kesten"],
		"email" : ["Email Address: ", "michael.k@sdofin.com"],
		"phone" : ["Phone Number: ", "(413)393-0000"],
		"contactType" : ["Contact Type: ", "Dealer"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "80"],
		"supportType" : ["Support Type: ", "Online_Chat"],
		"response" : ["Waiting for Response: ", "No"],
		"comments" : ["Support Overview: ", "At customers site, had connection issues but was resolved."]
	},
		"ticket13": {
		"date" : ["Date Entered: ", "2013-03-01"],
		"firstn" : ["First Name: ", "Amber"],
		"lastn" : ["Last Name: ", "Peterson"],
		"email" : ["Email Address: ", "amber.p@google.com"],
		"phone" : ["Phone Number: ", "(555)666-4444"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "10"],
		"supportType" : ["Support Type: ", "Email"],
		"response" : ["Waiting for Response: ", "No"],
		"comments" : ["Support Overview: ", "Defective motherboard."]
	},
		"ticket14": {
		"date" : ["Date Entered: ", "2013-02-27"],
		"firstn" : ["First Name: ", "Cory"],
		"lastn" : ["Last Name: ", "Morlocking"],
		"email" : ["Email Address: ", "c.d@compix.tv"],
		"phone" : ["Phone Number: ", "(949)525-0055"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "75"],
		"supportType" : ["Support Type: ", "Online_Chat"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "defective CPU"]
	},
		"ticket15": {
		"date" : ["Date Entered: ", "2013-02-27"],
		"firstn" : ["First Name: ", "Jeremy"],
		"lastn" : ["Last Name: ", "Hudec"],
		"email" : ["Email Address: ", "jh@gsdf.com"],
		"phone" : ["Phone Number: ", "(949)585-3055"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "75"],
		"supportType" : ["Support Type: ", "Email"],
		"response" : ["Waiting for Response: ", "No"],
		"comments" : ["Support Overview: ", "no video output"]
	},
		"ticket16": {
		"date" : ["Date Entered: ", "2013-02-27"],
		"firstn" : ["First Name: ", "Oliver"],
		"lastn" : ["Last Name: ", "Reyes"],
		"email" : ["Email Address: ", "oliver.reyes@compix.tv"],
		"phone" : ["Phone Number: ", "(949)585-0055"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "100"],
		"supportType" : ["Support Type: ", "Online_Chat"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "Helped with software, GenCG, issues."]
	},
		"ticket17": {
		"date" : ["Date Entered: ", "2013-02-27"],
		"firstn" : ["First Name: ", "Barry"],
		"lastn" : ["Last Name: ", "Page"],
		"email" : ["Email Address: ", "b.r@sdf.tv"],
		"phone" : ["Phone Number: ", "(949)585-2342"],
		"contactType" : ["Contact Type: ", "Dealer"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "100"],
		"supportType" : ["Support Type: ", "Call"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "is waiting for dealer to come and help him out.  Could not help over the phone."]
	},
		"ticket18": {
		"date" : ["Date Entered: ", "2013-02-26"],
		"firstn" : ["First Name: ", "Danny"],
		"lastn" : ["Last Name: ", "Wisneiwksi"],
		"email" : ["Email Address: ", "d.w@compix.tv"],
		"phone" : ["Phone Number: ", "(949)222-3393"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "75"],
		"supportType" : ["Support Type: ", "Call"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "NewsScroll is not function.  Restarted and it's back up and running again."]
	},
		"ticket19": {
		"date" : ["Date Entered: ", "2013-02-26"],
		"firstn" : ["First Name: ", "Lance"],
		"lastn" : ["Last Name: ", "Hupick"],
		"email" : ["Email Address: ", "d.s@compix.com"],
		"phone" : ["Phone Number: ", "(949)512-0055"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "25"],
		"supportType" : ["Support Type: ", "Call"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "Channel went down, had to restart system  Is in working order."]
	},
		"ticket20": {
		"date" : ["Date Entered: ", "2013-02-25"],
		"firstn" : ["First Name: ", "Jaehan"],
		"lastn" : ["Last Name: ", "Sudings"],
		"email" : ["Email Address: ", "s.d@sdfdsss.tv"],
		"phone" : ["Phone Number: ", "(949)233-0055"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "0"],
		"supportType" : ["Support Type: ", "Call"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "Unit is defective, requested to purchase new unit."]
	},
		"ticket21": {
		"date" : ["Date Entered: ", "2013-02-25"],
		"firstn" : ["First Name: ", "Veronica"],
		"lastn" : ["Last Name: ", "Kim"],
		"email" : ["Email Address: ", "veronica.kim@compix.tv"],
		"phone" : ["Phone Number: ", "(949)585-0055"],
		"contactType" : ["Contact Type: ", "Dealer"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "25"],
		"supportType" : ["Support Type: ", "Email"],
		"response" : ["Waiting for Response: ", "No"],
		"comments" : ["Support Overview: ", "Emailed in about sync issues with hardware."]
	},
		"ticket22": {
		"date" : ["Date Entered: ", "2013-02-25"],
		"firstn" : ["First Name: ", "Dan"],
		"lastn" : ["Last Name: ", "Palmer"],
		"email" : ["Email Address: ", "dan.p@timewarner.com"],
		"phone" : ["Phone Number: ", "(333)444-0055"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "100"],
		"supportType" : ["Support Type: ", "Call"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "GenCG Error, had to restart but it waiting for call back."]
	},
		"ticket23": {
		"date" : ["Date Entered: ", "2013-02-25"],
		"firstn" : ["First Name: ", "Graham"],
		"lastn" : ["Last Name: ", "Conda"],
		"email" : ["Email Address: ", "g.c@pink.edu"],
		"phone" : ["Phone Number: ", "(949)585-2345"],
		"contactType" : ["Contact Type: ", "Dealer"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "92"],
		"supportType" : ["Support Type: ", "Sales_Inquiry"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "Called about sales, will transfer when I get in."]
	},
		"ticket24": {
		"date" : ["Date Entered: ", "2013-02-24"],
		"firstn" : ["First Name: ", "Timothy"],
		"lastn" : ["Last Name: ", "Reyes"],
		"email" : ["Email Address: ", "tim.reyes@compix.tv"],
		"phone" : ["Phone Number: ", "(949)585-0055"],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "75"],
		"supportType" : ["Support Type: ", "Call"],
		"response" : ["Waiting for Response: ", "Yes"],
		"comments" : ["Support Overview: ", "While helping customer, found a couple bugs in software, will report accordingly."]
	},
		"ticket25": {
		"date" : ["Date Entered: ", "2013-02-23"],
		"firstn" : ["First Name: ", "Marc"],
		"lastn" : ["Last Name: ", "Perello"],
		"email" : ["Email Address: ", "maperall0@fcps.edu"],
		"phone" : ["Phone Number: ", ""],
		"contactType" : ["Contact Type: ", "End User"],
		"contactFeelings" : ["Contact Feelings Happy: 0 ~ Upset: 100: ", "50"],
		"supportType" : ["Support Type: ", "Online_Chat"],
		"response" : ["Waiting for Response: ", "No"],
		"comments" : ["Support Overview: ", "LCG5000D, problem with unit."]
	}
	
}